version: '2'
services:
    node-server:
        build: .
        ports:
          - "5000:5000"
        networks:
          tweetery-network:
            ipv4_address: "172.18.0.2"
        restart: unless-stopped
          
    redis-server:
        image: redis
        ports:
          - "6379:6379"
        networks:
          tweetery-network:
            ipv4_address: "172.18.0.3"
        restart: unless-stopped

networks:
  tweetery-network:
    driver: bridge
    ipam: 
      config:
        - subnet: 172.18.0.0/16
